```{r}
#| label: overtimefunc
#| cache: true
#| cache.comments: false

overtimefunc <- function(data, xvar = NULL, leglab = NULL, ybreaks = seq(0, 100, 25)) {
  if (is.null(xvar)) {
    data <- data %>%
      filter(is.na(xvars) & time >= ymd("2022-10-01"))

    datalabel <- data %>%
      filter(day(time) == 1) %>%
      arrange(shf_ef_cat, time) %>%
      slice(seq(3, n(), 3))

    p <- ggplot(
      data,
      aes(x = time, y = per, color = shf_ef_cat)
    ) +
      geom_step(linewidth = 1) +
      scale_color_manual(values = c(global_cols[1:3])) +
      scale_x_date(
        date_breaks = "3 months", date_labels = "%d/%m/%y"
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
      ) +
      labs(x = "Day/Month/Year", y = "Percent (%)") +
      geom_text_repel(data = datalabel, aes(x = time, y = per, label = perprint, color = shf_ef_cat), show.legend = FALSE, size = 5, fontface = "bold", inherit.aes = F, direction = "y")
  } else {
    data <- data %>%
      filter(!is.na(xvars) & xvars == xvar & time >= ymd("2022-10-01")) %>%
      mutate(xval = forcats::fct_inorder(xval))

    datalabel <- data %>%
      filter(day(time) == 1) %>%
      arrange(shf_ef_cat, xval, time) %>%
      slice(seq(3, n(), 3))

    p <- ggplot(
      data,
      aes(x = time, y = per, color = xval)
    ) +
      geom_step(linewidth = 1) +
      scale_color_manual(values = c(global_cols[1:3])) +
      scale_x_date(
        date_breaks = "3 months", date_labels = "%d/%m/%y"
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        legend.title = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
        panel.border = element_rect(fill = NA)
      ) +
      labs(x = "Day/Month/Year", y = "Percent (%)", color = leglab) +
      geom_text_repel(data = datalabel, aes(x = time, y = per, label = perprint, color = xval), show.legend = FALSE, size = 5, fontface = "bold", inherit.aes = F, direction = "y") +
      facet_wrap(vars(shf_ef_cat), nrow = 3, strip.position = "right")
  }

  if (pptx) {
    create_pptx(p)
  }
  p
}
```

```{r}
#| label: fig-overtime-prev
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Prevalent use of SGLT2i over time"
#| fig-subcap: !expr c("EF", subgroupvars_rs$label)
#| layout-ncol: 2
#| layout-nrow: 4

overtime_prev <- overtime_prev %>%
  mutate(
    xval = str_replace_all(xval, ">=", "\u2265"),
    xval = str_replace_all(xval, "<=", "\u2264")
  )

overtimefunc(data = overtime_prev)

nr <- 1
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr])

nr <- 2
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 3
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 4
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 5
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 6
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr])

nr <- 7
overtimefunc(data = overtime_prev, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])
```

```{r}
#| label: fig-overtime-inc
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Initiation of SGLT2i over time"
#| fig-subcap: !expr c("EF", subgroupvars_rs$label)
#| layout-ncol: 2
#| layout-nrow: 4

overtime_inc <- overtime_inc %>%
  mutate(
    xval = str_replace_all(xval, ">=", "\u2265"),
    xval = str_replace_all(xval, "<=", "\u2264")
  )

overtimefunc(data = overtime_inc)

nr <- 1
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr])

nr <- 2
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 3
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 4
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 5
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 6
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr])

nr <- 7
overtimefunc(data = overtime_inc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])
```

```{r}
#| label: fig-overtime-disc
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Discontinuation of SGLT2i over time"
#| fig-subcap: !expr c("EF", subgroupvars_rs$label)
#| layout-ncol: 2
#| layout-nrow: 4

overtime_disc <- overtime_disc %>%
  mutate(
    xval = str_replace_all(xval, ">=", "\u2265"),
    xval = str_replace_all(xval, "<=", "\u2264")
  )

overtimefunc(data = overtime_disc, ybreaks = seq(0, 20, 5))

nr <- 1
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], ybreaks = seq(0, 20, 5))

nr <- 2
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr], ybreaks = seq(0, 20, 5))

nr <- 3
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr], ybreaks = seq(0, 20, 5))

nr <- 4
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr], ybreaks = seq(0, 20, 5))

nr <- 5
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr], ybreaks = seq(0, 20, 5))

nr <- 6
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], ybreaks = seq(0, 20, 5))

nr <- 7
overtimefunc(data = overtime_disc, xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr], ybreaks = seq(0, 20, 5))
```
