```{r}
#| label: overtimefunc
#| cache: true
#| cache.comments: false

cols <- RColorBrewer::brewer.pal(9, "PuBu")

overtimefunc <- function(data = rsdataovertime, xvar, leglab = NULL, ybreaks = seq(0, 100, 25)) {
  if (xvar == "overall") {
    data <- data %>%
      group_by(shf_indexyearmonth, .drop = F) %>%
      count(sos_lm_sglt2, .drop = F) %>%
      mutate(per = n / sum(n) * 100) %>%
      ungroup() %>%
      filter(sos_lm_sglt2 == "Yes")

    datalab <- data %>%
      arrange(shf_indexyearmonth) %>%
      filter(shf_indexyearmonth %in% c("Nov 2020", "Sept 2022", "Dec 2024")) %>%
      mutate(perprint = fn(per, 0)) %>%
      ungroup()

    p <- ggplot(
      data,
      aes(x = shf_indexyearmonth, y = per)
    ) +
      geom_line(linewidth = 2, group = 1, color = cols[8]) +
      scale_color_manual(values = c(global_cols[1])) +
      scale_x_discrete(
        breaks = datalab %>% pull(shf_indexyearmonth), expand = c(0.06, 0.06)
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major.x = element_line(
          color = "darkgrey",
          linewidth = 1,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
      ) +
      labs(x = "Month Year", y = "Percent") +
      geom_text_repel(
        data = datalab, aes(x = shf_indexyearmonth, y = per, label = perprint), color = cols[8],
        show.legend = FALSE, size = 6, fontface = "bold", inherit.aes = F, direction = "y"
      )
  } else if (xvar == "ef") {
    data <- data %>%
      group_by(shf_ef_cat, shf_indexyearmonth, .drop = F) %>%
      count(sos_lm_sglt2, .drop = F) %>%
      mutate(per = n / sum(n) * 100) %>%
      ungroup() %>%
      filter(sos_lm_sglt2 == "Yes")

    datalab <- data %>%
      group_by(shf_ef_cat) %>%
      arrange(shf_indexyearmonth) %>%
      filter(shf_indexyearmonth %in% c("Nov 2020", "Sept 2022", "Dec 2024")) %>%
      mutate(perprint = fn(per, 0)) %>%
      ungroup()

    p <- ggplot(
      data,
      aes(x = shf_indexyearmonth, y = per, group = shf_ef_cat)
    ) +
      geom_line(aes(color = shf_ef_cat), linewidth = 2) +
      scale_color_manual(values = c(cols[c(9, 7, 5)])) +
      scale_x_discrete(
        breaks = datalab %>% pull(shf_indexyearmonth), expand = c(0.06, 0.06)
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major.x = element_line(
          color = "darkgrey",
          linewidth = 1,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
      ) +
      labs(x = "Month Year", y = "Percent") +
      geom_text_repel(
        data = datalab, aes(x = shf_indexyearmonth, y = per, label = perprint, color = shf_ef_cat),
        show.legend = FALSE, size = 6, fontface = "bold", inherit.aes = F, direction = "y"
      )
  } else {
    if (xvar == "sos_lm_sglt2type") {
      data <- data %>%
        filter(sos_lm_sglt2type != "Both") %>%
        mutate(sos_lm_sglt2type = droplevels(sos_lm_sglt2type)) %>%
        group_by(shf_ef_cat, shf_indexyearmonth, .drop = F) %>%
        count(sos_lm_sglt2type, .drop = F) %>%
        mutate(per = n / sum(n) * 100) %>%
        ungroup() %>%
        filter(sos_lm_sglt2type != "None")
    } else {
      data <- data %>%
        filter(!is.na(!!sym(xvar))) %>%
        group_by(shf_ef_cat, !!sym(xvar), shf_indexyearmonth, .drop = F) %>%
        count(sos_lm_sglt2, .drop = F) %>%
        mutate(
          per = n / sum(n) * 100,
          !!sym(xvar) := str_replace_all(!!sym(xvar), ">=", "\u2265"),
          !!sym(xvar) := str_replace_all(!!sym(xvar), "<=", "\u2264"),
          !!sym(xvar) := fct_inorder(!!sym(xvar))
        ) %>%
        ungroup() %>%
        filter(sos_lm_sglt2 == "Yes")
    }
    datalab <- data %>%
      group_by(shf_ef_cat, !!sym(xvar)) %>%
      arrange(shf_indexyearmonth) %>%
      filter(shf_indexyearmonth %in% c("Nov 2020", "Sept 2022", "Dec 2024")) %>%
      mutate(perprint = fn(per, 0)) %>%
      ungroup()

    ybreaks <- seq(0, 100, 50)

    p <- ggplot(
      data,
      aes(x = shf_indexyearmonth, y = per, group = !!sym(xvar))
    ) +
      geom_line(aes(color = !!sym(xvar)), linewidth = 2) +
      scale_color_manual(values = c(cols[c(9, 7, 5)])) +
      scale_x_discrete(
        breaks = datalab %>% pull(shf_indexyearmonth)
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major.x = element_line(
          color = "darkgrey",
          linewidth = 1,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        legend.title = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
        panel.border = element_rect(fill = NA)
      ) +
      labs(x = "Month Year", y = "Percent", color = leglab) +
      geom_text_repel(
        data = datalab, aes(x = shf_indexyearmonth, y = per, label = perprint, color = !!sym(xvar)),
        show.legend = FALSE, size = 6, fontface = "bold", inherit.aes = F, direction = "y"
      ) +
      facet_wrap(vars(shf_ef_cat), nrow = 3, strip.position = "right")
  }

  if (pptx) {
    if (xvar %in% c("overall", "ef")) {
      create_pptx(p)
    } else {
      create_pptx(p, width = 10, height = 10)
    }
  }
  p
}
```

```{r}
#| label: fig-overtime-prev-1
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Temporal trends of SGLT2i use"
#| fig-subcap:
#|  - "Overall"
#|  - "EF"
#| layout-ncol: 2
#| layout-nrow: 1

overtimefunc(xvar = "overall")

overtimefunc(xvar = "ef")
```


```{r}
#| label: fig-overtime-prev-2
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Temporal trends of SGLT2i use - continued"
#| fig-subcap:
#|  - "Sex"
#|  - "Age"
#|  - "eGFR"
#|  - "Diabetes"
#| layout-ncol: 2
#| layout-nrow: 2
#| fig-width: 10
#| fig-height: 10

nr <- 1
overtimefunc(xvar = subgroupvars$variable[nr])

nr <- 2
overtimefunc(xvar = subgroupvars$variable[nr], leglab = subgroupvars$labelunit[nr])

nr <- 3
overtimefunc(xvar = subgroupvars$variable[nr], leglab = subgroupvars$labelunit[nr])

nr <- 4
overtimefunc(xvar = subgroupvars$variable[nr], leglab = subgroupvars$labelunit[nr])
```

```{r}
#| label: fig-overtime-prev-3
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc
#| fig-cap: "Temporal trends of SGLT2i use - continued"
#| fig-subcap:
#| - "Previous HFH < 1 year"
#| - "Location"
#| - "Duration of HF"
#| - "SGLT2i type"
#| layout-ncol: 2
#| layout-nrow: 2
#| fig-width: 10
#| fig-height: 10

nr <- 5
overtimefunc(xvar = subgroupvars$variable[nr], leglab = subgroupvars$labelunit[nr])

nr <- 6
overtimefunc(xvar = subgroupvars$variable[nr])

nr <- 7
overtimefunc(xvar = subgroupvars$variable[nr], leglab = subgroupvars$labelunit[nr])

nr <- 8
overtimefunc(xvar = "sos_lm_sglt2type")
```
