```{r}
#| label: overtimefunc-alt
#| cache: true
#| cache.comments: false

datalab <- rsdata %>%
  select(shf_indexyearmonth) %>%
  distinct() %>%
  arrange(shf_indexyearmonth) %>%
  slice(seq(1, 16, 3))

overtimefunc <- function(data = rsdata, xvar = NULL, leglab = NULL, ybreaks = seq(0, 100, 25)) {
  if (is.null(xvar)) {
    data <- data %>%
      group_by(shf_ef_cat, shf_indexyearmonth) %>%
      count(sos_lm_sglt2) %>%
      mutate(per = n / sum(n) * 100) %>%
      ungroup() %>%
      filter(sos_lm_sglt2 == "Yes")

    p <- ggplot(
      data,
      aes(x = shf_indexyearmonth, y = per, group = shf_ef_cat)
    ) +
      geom_line(aes(color = shf_ef_cat), linewidth = 1) +
      geom_point(aes(color = shf_ef_cat), size = 2.5) +
      scale_color_manual(values = c(global_cols[1:3])) +
      scale_x_discrete(
        breaks = datalab %>% pull(shf_indexyearmonth), expand = c(0.06, 0.06)
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        # axis.text.x = element_text(angle = 90),
        legend.title = element_blank(),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
      ) +
      labs(x = "Month Year", y = "Percent (%)") #+
    # geom_text_repel(data = datalabel, aes(x = time, y = per, label = perprint, color = shf_ef_cat), show.legend = FALSE, size = 5, fontface = "bold", inherit.aes = F, direction = "y")
  } else {
    data <- data %>%
      filter(!is.na(!!sym(xvar))) %>%
      group_by(shf_ef_cat, !!sym(xvar), shf_indexyearmonth) %>%
      count(sos_lm_sglt2) %>%
      mutate(per = n / sum(n) * 100) %>%
      ungroup() %>%
      filter(sos_lm_sglt2 == "Yes")

    p <- ggplot(
      data,
      aes(x = shf_indexyearmonth, y = per, group = !!sym(xvar))
    ) +
      geom_line(aes(color = !!sym(xvar)), linewidth = 1) +
      geom_point(aes(color = !!sym(xvar)), size = 2.5) +
      scale_color_manual(values = c(global_cols[1:3])) +
      scale_x_discrete(
        breaks = datalab %>% pull(shf_indexyearmonth)
      ) +
      scale_y_continuous(
        limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
      ) +
      theme_classic() +
      theme(
        panel.grid.major = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 20, face = "bold"),
        legend.position = "bottom",
        # axis.text.x = element_text(angle = 90),
        legend.title = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(color = "black"),
        panel.border = element_rect(fill = NA)
      ) +
      labs(x = "Month Year", y = "Percent (%)", color = leglab) +
      # geom_text_repel(data = datalabel, aes(x = time, y = per, label = perprint, color = xval), show.legend = FALSE, size = 5, fontface = "bold", inherit.aes = F, direction = "y") +
      facet_wrap(vars(shf_ef_cat), nrow = 3, strip.position = "right")
  }

  if (pptx) {
    create_pptx(p)
  }
  p
}
```

```{r}
#| label: fig-overtime-prev-alt
#| cache: true
#| cache.comments: false
#| dependson: overtimefunc-alt
#| fig-cap: "Prevalent use of SGLT2i over time - Alternative (SGLT2i use at index only)"
#| fig-subcap: !expr c("EF", subgroupvars_rs$label)
#| layout-ncol: 2
#| layout-nrow: 4

overtimefunc()

nr <- 1
overtimefunc(xvar = subgroupvars_rs$variable[nr])

nr <- 2
overtimefunc(xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 3
overtimefunc(xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 4
overtimefunc(xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 5
overtimefunc(xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])

nr <- 6
overtimefunc(xvar = subgroupvars_rs$variable[nr])

nr <- 7
overtimefunc(xvar = subgroupvars_rs$variable[nr], leglab = subgroupvars_rs$labelunit[nr])
```
