```{r}
#| label: predictorsfunc
#| cache: true
#| cache.comments: false

predictorsfunc <- function(impdata = imprsdata, novars = NULL) {
  modvarstmp <- setdiff(modvars, novars)

  levsef <- levels(rsdata %>% pull(shf_ef_cat))
  for (i in seq_along(modvarstmp)) {
    for (j in seq_along(levsef)) {
      # adjusted
      modvarstmp2 <- modvarstmp[!modvarstmp %in% c(modvarstmp[i])]
      levs <- levels(rsdata %>% pull(!!sym(modvarstmp[i])))
      nlevs <- length(levs)
      logreg <- with(impdata, glm(
        formula(paste0(
          "sos_lm_sglt2 == 'Yes' ~ ", modvarstmp[i], " * relevel(shf_ef_cat, ref = '",
          levsef[j], "') + ",
          paste(modvarstmp2, collapse = " + ")
        )),
        family = binomial(link = "logit")
      ))
      logregsum <- summary(pool(logreg))

      if (j == 3) {
        logreg_noint <- with(impdata, glm(
          formula(paste0(
            "sos_lm_sglt2 == 'Yes' ~ ", modvarstmp[i], " + relevel(shf_ef_cat, ref = '",
            levsef[j], "') + ",
            paste(modvarstmp2, collapse = " + ")
          )),
          family = binomial(link = "logit")
        ))

        # and compare
        pint <- mice::D1(logreg, logreg_noint)
        pint <- fn(pint$result[, "P(>F)"], p = T, dig = 3)
      } else {
        pint <- NA
      }
      if (nlevs == 2) {
        adjtmp <- tibble(
          var = modvarstmp[i],
          lev = paste0(levs[2:nlevs], " vs ", levs[1]),
          or = exp(logregsum$estimate[2:nlevs]),
          lci = exp(logregsum$estimate[2:nlevs] - global_z05 * logregsum$std.error[2:nlevs]),
          uci = exp(logregsum$estimate[2:nlevs] + global_z05 * logregsum$std.error[2:nlevs]),
          p = fn(logregsum$p.value[2:nlevs], dig = 3, p = TRUE),
          ef = levsef[j],
          pint = pint
        ) %>%
          mutate(cols = case_when(
            logregsum$p.value[2:nlevs] >= 0.05 ~ 2,
            or >= 1 ~ 1,
            or < 1 ~ 3
          ))
      } else {
        adjtmp <- tibble(
          var = c(modvarstmp[i], rep(NA, nlevs - 1)),
          lev = c(NA, paste0("  ", levs[2:nlevs], " vs ", levs[1])),
          or = c(NA, exp(logregsum$estimate[2:nlevs])),
          lci = c(NA, exp(logregsum$estimate[2:nlevs] - global_z05 * logregsum$std.error[2:nlevs])),
          uci = c(NA, exp(logregsum$estimate[2:nlevs] + global_z05 * logregsum$std.error[2:nlevs])),
          p = c(NA, fn(logregsum$p.value[2:nlevs], dig = 3, p = TRUE)),
          ef = levsef[j],
          pint = c(pint, rep(NA, nlevs - 1))
        ) %>%
          mutate(cols = case_when(
            c(NA, logregsum$p.value[2:nlevs]) >= 0.05 ~ 2,
            or >= 1 ~ 1,
            or < 1 ~ 3
          ))
      }
      # crude
      logreg <- with(impdata, glm(
        formula(paste0(
          "sos_lm_sglt2 == 'Yes' ~ ", modvarstmp[i], " * relevel(shf_ef_cat, ref = '",
          levsef[j], "')"
        )),
        family = binomial(link = "logit")
      ))
      logregsum <- summary(pool(logreg))

      if (j == 3) {
        logreg_noint <- with(impdata, glm(
          formula(paste0(
            "sos_lm_sglt2 == 'Yes' ~ ", modvarstmp[i], " + relevel(shf_ef_cat, ref = '",
            levsef[j], "')"
          )),
          family = binomial(link = "logit")
        ))

        # and compare
        pint <- mice::D1(logreg, logreg_noint)
        pint <- fn(pint$result[, "P(>F)"], p = T, dig = 3)
      } else {
        pint <- NA
      }
      if (nlevs == 2) {
        crudetmp <- tibble(
          var = modvarstmp[i],
          lev = paste0(levs[2:nlevs], " vs ", levs[1]),
          or = exp(logregsum$estimate[2:nlevs]),
          lci = exp(logregsum$estimate[2:nlevs] - global_z05 * logregsum$std.error[2:nlevs]),
          uci = exp(logregsum$estimate[2:nlevs] + global_z05 * logregsum$std.error[2:nlevs]),
          p = fn(logregsum$p.value[2:nlevs], dig = 3, p = TRUE),
          ef = levsef[j],
          pint = pint
        ) %>%
          mutate(cols = case_when(
            logregsum$p.value[2:nlevs] >= 0.05 ~ 2,
            or >= 1 ~ 1,
            or < 1 ~ 3
          ))
      } else {
        crudetmp <- tibble(
          var = c(modvarstmp[i], rep(NA, nlevs - 1)),
          lev = c(NA, paste0("  ", levs[2:nlevs], " vs ", levs[1])),
          or = c(NA, exp(logregsum$estimate[2:nlevs])),
          lci = c(NA, exp(logregsum$estimate[2:nlevs] - global_z05 * logregsum$std.error[2:nlevs])),
          uci = c(NA, exp(logregsum$estimate[2:nlevs] + global_z05 * logregsum$std.error[2:nlevs])),
          p = c(NA, fn(logregsum$p.value[2:nlevs], dig = 3, p = TRUE)),
          ef = levsef[j],
          pint = c(pint, rep(NA, nlevs - 1))
        ) %>%
          mutate(cols = case_when(
            c(NA, logregsum$p.value[2:nlevs]) >= 0.05 ~ 2,
            or >= 1 ~ 1,
            or < 1 ~ 3
          ))
      }
      tmp <- bind_rows(
        crudetmp %>% mutate(model = "crude"),
        adjtmp %>% mutate(model = "adj")
      )

      if (i == 1 & j == 1) {
        predout <<- tmp
      } else {
        predout <<- bind_rows(predout, tmp)
      }
    }
  }

  # save <- predout
  # predout <- save
  predout <- predout %>%
    mutate(
      orci = if_else(!is.na(or), paste0(
        fn(or, 2), " (",
        fn(lci, 2), "-",
        fn(uci, 2), ")"
      ), NA),
      cols = factor(cols, levels = 1:3),
      var = str_remove_all(var, fixed("Yes")),
      var = str_remove_all(var, "(_cat2|_cat)")
    )

  predout <- left_join(predout,
    metavars %>%
      select(variable, label, unit),
    by = c("var" = "variable")
  ) %>%
    mutate(
      unit = if_else(label == "Disposable income", NA, unit),
      var = coalesce(label, var),
      var = if_else(!is.na(unit),
        paste0(var, " (", unit, ")"),
        var
      ),
      var2 = case_when(
        lev == "Yes vs No" | is.na(lev) ~ var,
        var %in% c("Sex", "Family situation", "Device therapy", "Location") ~ lev,
        !is.na(lev) & !is.na(var) ~ paste0(var, " ", lev),
        TRUE ~ lev
      ),
      # minor manual fixes
      var2 = case_when(
        var2 == "Malignant cancer within 3 years" ~ "Malignant cancer",
        var2 == "  Secondary school vs Compulsory school" ~ "  Secondary vs Compulsory school",
        var2 == "  2nd tertile within year vs 1st tertile within year" ~ "  2nd tertile vs 1st tertile within year",
        var2 == "  3rd tertile within year vs 1st tertile within year" ~ "  3rd tertile vs 1st tertile within year",
        var2 == "Follow-up referral speciality Hospital vs Primary care/Other" ~ "Follow-up referral Hospital vs PC/Other",
        var2 == "Systolic blood pressure (mmHg) >=140 vs <140" ~ "Systolic bp (mmHg) >=140 vs <140",
        TRUE ~ var2
      )
    )
}

predout <- predictorsfunc()
```

```{r}
#| label: fig-predictors
#| cache: true
#| cache.comments: false
#| dependson: predictorsfunc
#| fig-cap: "Independent associations between baseline characteristics and SGLT2i"
#| fig-width: 10
#| fig-height: 10

predoutplot <- predout %>%
  mutate(
    var2 = str_replace_all(var2, ">=", "\u2265"),
    var2 = str_replace_all(var2, "<=", "\u2264"),
    var2 = forcats::fct_rev(forcats::fct_inorder(var2)),
    cols = forcats::fct_rev(cols)
  )

# plot it
size_use <- 10

# min(predout$lci)
# max(predout$uci)

xmin <- .2
xmax <- 5

p1 <- ggplot(predoutplot %>% filter(ef == "HFrEF" & model == "adj"), aes(x = or, y = var2, color = cols)) +
  # Add a reference dashed line at 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey", linewidth = 0.6) +
  # Add dot plot and error bars
  geom_errorbar(aes(xmin = lci, xmax = uci), width = 0, linewidth = 0.5) +
  geom_point(size = 1.5, shape = 15) +
  scale_color_manual(values = global_cols[c(1, 2, 3)]) +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.text.x = element_text(color = "black"),
    panel.grid.major.y = element_line(colour = "grey94")
  ) +
  scale_x_continuous(trans = "log", breaks = c(xmin, 1, xmax), limits = c(xmin, xmax))

t1 <- ggplot(predoutplot %>% filter(ef == "HFrEF" & model == "adj")) +
  geom_text(aes(y = var2, x = 1, label = orci), size = size_use / .pt * 0.8, fontface = "bold") +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  )


p2 <- ggplot(predoutplot %>% filter(ef == "HFmrEF" & model == "adj"), aes(x = or, y = var2, color = cols)) +
  # Add a reference dashed line at 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey", linewidth = 0.6) +
  # Add dot plot and error bars
  geom_errorbar(aes(xmin = lci, xmax = uci), width = 0, linewidth = 0.5) +
  geom_point(size = 1.5, shape = 15) +
  scale_color_manual(values = global_cols[c(1, 2, 3)]) +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.text.x = element_text(color = "black"),
    panel.grid.major.y = element_line(colour = "grey94")
  ) +
  scale_x_continuous(trans = "log", breaks = c(xmin, 1, xmax), limits = c(xmin, xmax))

t2 <- ggplot(predoutplot %>% filter(ef == "HFmrEF" & model == "adj")) +
  geom_text(aes(y = var2, x = 1, label = orci), size = size_use / .pt * 0.8, fontface = "bold") +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  )

p3 <- ggplot(predoutplot %>% filter(ef == "HFpEF" & model == "adj"), aes(x = or, y = var2, color = cols)) +
  # Add a reference dashed line at 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey", linewidth = 0.6) +
  # Add dot plot and error bars
  geom_errorbar(aes(xmin = lci, xmax = uci), width = 0, linewidth = 0.5) +
  geom_point(size = 1.5, shape = 15) +
  scale_color_manual(values = global_cols[c(1, 2, 3)]) +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.text.x = element_text(color = "black"),
    panel.grid.major.y = element_line(colour = "grey94")
  ) +
  scale_x_continuous(trans = "log", breaks = c(xmin, 1, xmax), limits = c(xmin, xmax))

t3 <- ggplot(predoutplot %>% filter(ef == "HFpEF" & model == "adj")) +
  geom_text(aes(y = var2, x = 1, label = orci), size = size_use / .pt * 0.8, fontface = "bold") +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  )


labs <- ggplot(predoutplot %>% filter(ef == "HFpEF" & model == "adj"), aes(x = or, y = var2)) +
  geom_blank() +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_text(color = "black", hjust = 0),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  )

pint <- ggplot(predoutplot %>% filter(ef == "HFpEF" & model == "adj")) +
  geom_text(aes(y = var2, x = 1, label = pint), size = size_use / .pt * 0.8, fontface = "bold") +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  )

pall1 <- p1 + t1 +
  plot_annotation(
    title = "HFrEF",
    subtitle = "Odds Ratio (95% CI)",
    theme = theme(
      text = element_text(size = size_use, face = "bold"),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
  )

pall2 <- p2 + t2 +
  plot_annotation(
    title = "HFmrEF",
    subtitle = "Odds Ratio (95% CI)",
    theme = theme(
      text = element_text(size = size_use, face = "bold"),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
  )

pall3 <- p3 + t3 +
  plot_annotation(
    title = "HFpEF",
    subtitle = "Odds Ratio (95% CI)",
    theme = theme(
      text = element_text(size = size_use, face = "bold"),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
  )

labs <- labs +
  plot_annotation(
    title = " ",
    subtitle = " ",
    theme = theme(
      text = element_text(size = size_use, face = "bold"),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
  )

pint <- pint +
  plot_annotation(
    title = " ",
    subtitle = "P interaction",
    theme = theme(
      text = element_text(size = size_use, face = "bold"),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
  )

pall <- wrap_elements(labs) + wrap_elements(pall1) + wrap_elements(pall2) + wrap_elements(pall3) + wrap_elements(pint) +
  plot_layout(nrow = 1, widths = c(3, 3.4, 3.4, 3.4, 1))

if (pptx) {
  create_pptx(pall, width = 10, height = 10)
}

pall
```


\blandscape

```{r}
#| label: tbl-predictors
#| cache: true
#| cache.comments: false
#| dependson: predictorsfunc
#| tbl-cap: "Associations between baseline characteristics and SGLT2i"
#| tbl-pos: "H"

predtab <- predout %>%
  select(var2, ef, model, orci, pint) %>%
  pivot_wider(names_from = c(model, ef), values_from = c(orci, pint)) %>%
  select(
    var2, orci_crude_HFrEF, orci_crude_HFmrEF, orci_crude_HFpEF, pint_crude_HFpEF,
    orci_adj_HFrEF, orci_adj_HFmrEF, orci_adj_HFpEF, pint_adj_HFpEF
  )

cn <- c("Variable", rep(c(levels(rsdata$shf_ef_cat), "P-value interaction"), 2))

make_one_xlsxsheet(predtab, colnames = cn)

indent_rows <- predtab %>%
  mutate(
    indent_rows = str_detect(var2, "  "),
    rows = row_number()
  ) %>%
  filter(indent_rows) %>%
  pull(rows)

cn <- sanitize_text(cn)

# footnotes
predtab <- predtab %>%
  mutate(
    # so no probs
    var2 = sanitize_text(var2),
    var2 = str_replace_all(var2, fixed("²"), "\\textsuperscript{2}"),
    var2 = str_replace_all(var2, fixed("$>$="), "$\\geq$"),
    var2 = str_replace_all(var2, fixed("$<$="), "$\\leq$")
  )

default_kable(predtab,
  font_size = 5,
  escape = FALSE,
  col.names = cn
) %>%
  add_indent(indent_rows) %>%
  add_header_above(c(" " = 1, "Crude Odds Ratio (95% CI)" = 4, "Adjusted Odds Ratio (95% CI)" = 4)) %>%
  column_spec(c(5, 9), width = "2cm")
```

\elandscape

```{r}
#| label: predictorsoverallfunc
#| cache: true
#| cache.comments: false

modvarstmp <- c("shf_ef_cat", modvars)
# adjusted
logregadj <- with(imprsdata, glm(
  formula(paste0(
    "sos_lm_sglt2 == 'Yes' ~ ", paste(modvarstmp, collapse = " + ")
  )),
  family = binomial(link = "logit")
))
logregsumadj <- summary(pool(logregadj))

adjtmp <- tibble(
  varname = as.character(logregsumadj$term),
  or = exp(logregsumadj$estimate),
  lci = exp(logregsumadj$estimate - global_z05 * logregsumadj$std.error),
  uci = exp(logregsumadj$estimate + global_z05 * logregsumadj$std.error),
  p = fn(logregsumadj$p.value, dig = 3, p = TRUE)
) %>%
  mutate(cols = case_when(
    logregsumadj$p.value >= 0.05 ~ 2,
    or >= 1 ~ 1,
    or < 1 ~ 3
  )) %>%
  slice(2:n())

for (i in seq_along(modvarstmp)) {
  # crude
  levs <- levels(rsdata %>% pull(!!sym(modvarstmp[i])))
  nlevs <- length(levs)
  logregcrude <- with(imprsdata, glm(
    formula(paste0(
      "sos_lm_sglt2 == 'Yes' ~ ", modvarstmp[i]
    )),
    family = binomial(link = "logit")
  ))
  logregsumcrude <- summary(pool(logregcrude))
  if (nlevs == 2) {
    tmp <- tibble(
      varname = as.character(logregsumcrude$term[2:nlevs]),
      var = modvarstmp[i],
      lev = paste0(levs[2:nlevs], " vs ", levs[1]),
      or = exp(logregsumcrude$estimate[2:nlevs]),
      lci = exp(logregsumcrude$estimate[2:nlevs] - global_z05 * logregsumcrude$std.error[2:nlevs]),
      uci = exp(logregsumcrude$estimate[2:nlevs] + global_z05 * logregsumcrude$std.error[2:nlevs]),
      p = fn(logregsumcrude$p.value[2:nlevs], dig = 3, p = TRUE)
    ) %>%
      mutate(cols = case_when(
        logregsumcrude$p.value[2:nlevs] >= 0.05 ~ 2,
        or >= 1 ~ 1,
        or < 1 ~ 3
      ))
  } else {
    tmp <- tibble(
      varname = c(NA, as.character(logregsumcrude$term[2:nlevs])),
      var = c(modvarstmp[i], rep(NA, nlevs - 1)),
      lev = c(NA, paste0("  ", levs[2:nlevs], " vs ", levs[1])),
      or = c(NA, exp(logregsumcrude$estimate[2:nlevs])),
      lci = c(NA, exp(logregsumcrude$estimate[2:nlevs] - global_z05 * logregsumcrude$std.error[2:nlevs])),
      uci = c(NA, exp(logregsumcrude$estimate[2:nlevs] + global_z05 * logregsumcrude$std.error[2:nlevs])),
      p = c(NA, fn(logregsumcrude$p.value[2:nlevs], dig = 3, p = TRUE))
    ) %>%
      mutate(cols = case_when(
        c(NA, logregsumcrude$p.value[2:nlevs]) >= 0.05 ~ 2,
        or >= 1 ~ 1,
        or < 1 ~ 3
      ))
  }

  if (i == 1) {
    crudetmp <<- tmp
  } else {
    crudetmp <<- bind_rows(crudetmp, tmp)
  }
}

crudetmp <- crudetmp %>%
  mutate(c = 1:n())


predoutoverall <- bind_rows(
  crudetmp %>% mutate(model = "crude"),
  adjtmp %>% mutate(model = "adj")
)

# save <- predoutoverall
# predoutoverall <- save
predoutoverall <- predoutoverall %>%
  mutate(
    orci = if_else(!is.na(or), paste0(
      fn(or, 2), " (",
      fn(lci, 2), "-",
      fn(uci, 2), ")"
    ), NA),
    cols = factor(cols, levels = 1:3),
    var = str_remove_all(var, fixed("Yes")),
    var = str_remove_all(var, "(_cat2|_cat)")
  )

predoutoverall <- left_join(predoutoverall,
  metavars %>%
    select(variable, label, unit),
  by = c("var" = "variable")
) %>%
  mutate(
    unit = if_else(label == "Disposable income", NA, unit),
    var = coalesce(label, var),
    var = if_else(!is.na(unit),
      paste0(var, " (", unit, ")"),
      var
    ),
    var2 = case_when(
      lev == "Yes vs No" | is.na(lev) ~ var,
      var %in% c("Sex", "Family situation", "Device therapy", "Location") ~ lev,
      !is.na(lev) & !is.na(var) ~ paste0(var, " ", lev),
      TRUE ~ lev
    ),
    # minor manual fixes
    var2 = case_when(
      var2 == "Malignant cancer within 3 years" ~ "Malignant cancer",
      var2 == "  Secondary school vs Compulsory school" ~ "  Secondary vs Compulsory school",
      var2 == "  2nd tertile within year vs 1st tertile within year" ~ "  2nd tertile vs 1st tertile within year",
      var2 == "  3rd tertile within year vs 1st tertile within year" ~ "  3rd tertile vs 1st tertile within year",
      var2 == "Follow-up referral speciality Hospital vs Primary care/Other" ~ "Follow-up referral Hospital vs PC/Other",
      var2 == "Systolic blood pressure (mmHg) >=140 vs <140" ~ "Systolic bp (mmHg) >=140 vs <140",
      TRUE ~ var2
    )
  )

predoutoverall2 <- full_join(
  predoutoverall %>% filter(model == "crude") %>% select(varname, var2, orci, c),
  predoutoverall %>% filter(model == "adj") %>% select(varname, or, lci, uci, cols, orci),
  by = "varname",
  suffix = c("_crude", "")
) %>%
  arrange(c)
```

```{r}
#| label: fig-predictors-overall
#| cache: true
#| cache.comments: false
#| dependson: predictorsoverallfunc
#| fig-cap: "Independent associations between baseline characteristics and SGLT2i - Overall"
#| fig-width: 7
#| fig-height: 10

predoutoverallplot <- predoutoverall2 %>%
  mutate(
    var2 = str_replace_all(var2, ">=", "\u2265"),
    var2 = str_replace_all(var2, "<=", "\u2264"),
    var2 = forcats::fct_rev(forcats::fct_inorder(var2)),
    cols = forcats::fct_rev(cols)
  )

# plot it
size_use <- 10

# min(predout$lci)
# max(predout$uci)

xmin <- .2
xmax <- 5

p1 <- ggplot(predoutoverallplot, aes(x = or, y = var2, color = cols)) +
  # Add a reference dashed line at 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey", linewidth = 0.6) +
  # Add dot plot and error bars
  geom_errorbar(aes(xmin = lci, xmax = uci), width = 0, linewidth = 0.5) +
  geom_point(size = 1.5, shape = 15) +
  scale_color_manual(values = global_cols[c(1, 2, 3)]) +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.text.x = element_text(color = "black"),
    panel.grid.major.y = element_line(colour = "grey94")
  ) +
  scale_x_continuous(trans = "log", breaks = c(xmin, 1, xmax), limits = c(xmin, xmax)) +
  labs(x = "Odds Ratio (95% CI)") +
  ggtitle(" ")

t1 <- ggplot(predoutoverallplot) +
  geom_text(aes(y = var2, x = 1, label = orci), size = size_use / .pt * 0.8, fontface = "bold") +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  ) +
  ggtitle("Odds Ratio (95% CI)")

labs <- ggplot(predoutoverallplot, aes(x = or, y = var2)) +
  geom_blank() +
  theme_classic() +
  theme(
    text = element_text(size = size_use, face = "bold"),
    legend.position = "none",
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_text(color = "black", hjust = 0),
    axis.line.y = element_line(colour = "white"),
    plot.margin = unit(c(0, 0, 0, 0), "mm"),
    axis.line.x = element_line(color = "white"),
    axis.ticks.x = element_line(color = "white"),
    axis.text.x = element_text(color = "white")
  ) +
  ggtitle(" ")

pall <- labs + p1 + t1 +
  plot_layout(nrow = 1)

if (pptx) {
  create_pptx(pall, width = 7, height = 10)
}

pall
```

```{r}
#| label: tbl-predictors-overall
#| cache: true
#| cache.comments: false
#| dependson: predictorsfunc
#| tbl-cap: "Associations between baseline characteristics and SGLT2i - Overall"
#| tbl-pos: "H"

predoveralltab <- predoutoverall2 %>%
  select(var2, orci_crude, orci)

cn <- c("Variable", "Crude Odds Ratio (95% CI)", "Adjusted Odds Ratio (95% CI)")

make_one_xlsxsheet(predoveralltab, colnames = cn)

indent_rows <- predoveralltab %>%
  mutate(
    indent_rows = str_detect(var2, "  "),
    rows = row_number()
  ) %>%
  filter(indent_rows) %>%
  pull(rows)

cn <- sanitize_text(cn)

predoveralltab <- predoveralltab %>%
  mutate(
    # so no probs
    var2 = sanitize_text(var2),
    var2 = str_replace_all(var2, fixed("²"), "\\textsuperscript{2}"),
    var2 = str_replace_all(var2, fixed("$>$="), "$\\geq$"),
    var2 = str_replace_all(var2, fixed("$<$="), "$\\leq$")
  )

default_kable(predoveralltab,
  escape = FALSE,
  col.names = cn
) %>%
  add_indent(indent_rows)
```
